[package]
name = "gammaray"
version = "0.1.0"
authors = ["steve"]

[[bin]]
name = "gammaray"

[profile.dev]
opt-level = 3

[dependencies]
rand = "0.3"
bitflags = "0.9.1"
rayon = "0.8.2"
byteorder = "1.1.0"
wavefront_obj = "5.1.0"
