[package]
name = "gammaray"
version = "0.1.0"
authors = ["steve"]

[[bin]]
name = "gammaray"

[profile.dev]
opt-level = 3

[dependencies]
rand = "0.3"
bitflags = "0.9.1"
gfx = "0.16"
glutin = "0.8"
gfx_window_glutin = "0.16"
rayon = "0.8.2"
